I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 677, in script
    show male bff concerned at rigth with easeinright
  File "game/script.rpy", line 677, in <module>
    show male bff concerned at rigth with easeinright
NameError: name 'rigth' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 677, in script
    show male bff concerned at rigth with easeinright
  File "renpy/ast.py", line 1191, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1150, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 677, in <module>
    show male bff concerned at rigth with easeinright
NameError: name 'rigth' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
Doki Doki President 2.0
Thu Feb 11 23:00:39 2021
